
// This file has been generated by the GUI designer. Do not modify.
namespace InvertikaEditor
{
	public partial class FormOptions
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget InvertikaEditor.FormOptions
			this.Name="InvertikaEditor.FormOptions";
			this.Title=global::Mono.Unix.Catalog.GetString("FormOptions");
			this.WindowPosition=((global::Gtk.WindowPosition)(4));
			if((this.Child!=null)) {
				this.Child.ShowAll();
			}
			this.DefaultWidth=400;
			this.DefaultHeight=300;
			this.Show();
		}
	}
}
