
// This file has been generated by the GUI designer. Do not modify.
namespace InvertikaEditor
{
	public partial class FormMain
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action DateiAction;
		private global::Gtk.Action BeendenAction;
		private global::Gtk.Action beendenAction;
		private global::Gtk.Action OptionenAction;
		private global::Gtk.Action OptionenAction1;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.Notebook notebook1;
		private global::Gtk.Label label1;
		private global::Gtk.Statusbar statusbar1;
        
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget InvertikaEditor.FormMain
			this.UIManager=new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1=new global::Gtk.ActionGroup("Default");
			this.DateiAction=new global::Gtk.Action("DateiAction", global::Mono.Unix.Catalog.GetString("Datei"), null, null);
			this.DateiAction.ShortLabel=global::Mono.Unix.Catalog.GetString("Datei");
			w1.Add(this.DateiAction, null);
			this.BeendenAction=new global::Gtk.Action("BeendenAction", global::Mono.Unix.Catalog.GetString("Beenden"), null, null);
			this.BeendenAction.ShortLabel=global::Mono.Unix.Catalog.GetString("Beenden");
			w1.Add(this.BeendenAction, null);
			this.beendenAction=new global::Gtk.Action("beendenAction", global::Mono.Unix.Catalog.GetString("beenden"), null, null);
			this.beendenAction.ShortLabel=global::Mono.Unix.Catalog.GetString("beenden");
			w1.Add(this.beendenAction, null);
			this.OptionenAction=new global::Gtk.Action("OptionenAction", global::Mono.Unix.Catalog.GetString("Optionen..."), null, null);
			this.OptionenAction.ShortLabel=global::Mono.Unix.Catalog.GetString("Optionen...");
			w1.Add(this.OptionenAction, null);
			this.OptionenAction1=new global::Gtk.Action("OptionenAction1", global::Mono.Unix.Catalog.GetString("Optionen..."), null, null);
			this.OptionenAction1.ShortLabel=global::Mono.Unix.Catalog.GetString("Optionen...");
			w1.Add(this.OptionenAction1, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name="InvertikaEditor.FormMain";
			this.Title=global::Mono.Unix.Catalog.GetString("FormMain");
			this.WindowPosition=((global::Gtk.WindowPosition)(4));
			// Container child InvertikaEditor.FormMain.Gtk.Container+ContainerChild
			this.vbox1=new global::Gtk.VBox();
			this.vbox1.Name="vbox1";
			this.vbox1.Spacing=6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><menubar name='menubar1'><menu name='DateiAction' action='DateiAction'><menuitem name='OptionenAction1' action='OptionenAction1'/><separator/><menuitem name='BeendenAction' action='BeendenAction'/></menu></menubar></ui>");
			this.menubar1=((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
			this.menubar1.Name="menubar1";
			this.vbox1.Add(this.menubar1);
			global::Gtk.Box.BoxChild w2=((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position=0;
			w2.Expand=false;
			w2.Fill=false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1=new global::Gtk.Notebook();
			this.notebook1.CanFocus=true;
			this.notebook1.Name="notebook1";
			this.notebook1.CurrentPage=0;
			// Notebook tab
			global::Gtk.Label w3=new global::Gtk.Label();
			w3.Visible=true;
			this.notebook1.Add(w3);
			this.label1=new global::Gtk.Label();
			this.label1.Name="label1";
			this.label1.LabelProp=global::Mono.Unix.Catalog.GetString("Questeditor");
			this.notebook1.SetTabLabel(w3, this.label1);
			this.label1.ShowAll();
			this.vbox1.Add(this.notebook1);
			global::Gtk.Box.BoxChild w4=((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
			w4.Position=1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1=new global::Gtk.Statusbar();
			this.statusbar1.Name="statusbar1";
			this.statusbar1.Spacing=6;
			this.vbox1.Add(this.statusbar1);
			global::Gtk.Box.BoxChild w5=((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w5.Position=2;
			w5.Expand=false;
			w5.Fill=false;
			this.Add(this.vbox1);
			if((this.Child!=null)) {
				this.Child.ShowAll();
			}
			this.DefaultWidth=438;
			this.DefaultHeight=325;
			this.Show();
			this.BeendenAction.Activated+=new global::System.EventHandler(this.OnBeendenActionActivated);
			this.OptionenAction1.Activated+=new global::System.EventHandler(this.OnOptionenAction1Activated);
		}
	}
}
